### ISSUE TITLE
Guide how to do video recording in selenium grid mode

### ISSUE THREAD

**Issue by luisxiaomai** [elgalu/docker-selenium#96] opened 2016-05-25 01:04 UTC
Hi,

Thanks for your sharing about this project, but I see your image is too large and both hub&node are in one container.

Suppose that I have 1 grid group with 12 nodes which are all in separate container, I have 12 test suites run parallelly in 12 nodes. How can I don video recording automatically for these 12 test suites?

Can your project can support above my assumption or give some other technical proposal? Thanks.

B.R.
Luis

**Comment by elgalu** [comment] 2016-05-25 08:02
Welcome. You will need wait for #77 and #78 for that. For now this image is only meant for running 1 test on each container in a standalone fashion, see https://github.com/elgalu/docker-selenium#official-repo

**Comment by chandrakanth1984** [comment] 2016-06-16 22:57
Hi Elgalu,

Are there any updates on this question?

We are also looking for this release to record multiple sessions.

Thanks,
Chandrakanth

**Comment by elgalu** [comment] 2016-06-17 16:37
Please subscribe to issue #77 to get updates but note is not being worked on now and there is not ETA, sorry about that, in general I work less than 5% of my time in this project.

**Comment by elgalu** [comment] 2016-09-29 14:36
Will close this one as duplicate of #77

**Closed by elgalu** 2016-09-29 14:36 UTC
Labels: question
