### ISSUE TITLE
VNC Performance Improvement

### ISSUE THREAD

**Issue by dring1** [elgalu/docker-selenium#150] opened 2017-05-05 19:25 UTC
Command and params used to run container:
```
docker run --rm -ti --name=grid -p 4444:24444 -p 5900:25900\
   --shm-size=1g -p 6080:26080 -e NOVNC=true -e VIDEO=true   elgalu/selenium
```

Currently experiencing quite a bit of choppiness when launching NoVNC, most noticeable with CSS transitions.

Looking through previous issues and docs yield few results, curious as to what folks have done to reduce the choppiness?

Are there params/options that could be increased that would affect the quality of the VNC ?

Note: this testing is all done over my localhost network 

Thanks.

**Comment by elgalu** [comment] 2017-05-08 14:50
Thanks for the feedback @dring1 

Do you also experience this with VNC alone? i.e. without noVNC and by using your own VNC client, perhaps RealVNC or some other good one?

**Comment by elgalu** [comment] 2017-05-08 14:54
Sorry just trying to identify where the problem is. To be honest we never cared much about having great viewing quality as the intention of it was to just see the tests running and when a tests fails, if we can't identify the reason by the logs and by the screenshots then only then see the video and identify the problem there, but never looked for top quality as it was never the purpose.

Yet if we can fix this I would love to.

Addition question: when you see the mkv/mp4 video do you also see the choppiness?

**Comment by dring1** [comment] 2017-05-08 15:13
Little to not choppiness in the recordings, which led me to believe this would be an issue with the VNC server itself.

Experienced the same choppiness with TightVNC Viewer.

**Comment by elgalu** [comment] 2017-05-08 15:42
Thanks for analyzing it.

Did you try to improve it VNC client side, e.g. by setting the compression options?
https://serverfault.com/a/64325/200544

**Comment by elgalu** [comment] 2017-05-08 15:55
If VNC client side tweaking fails then we need to look into the VNC server settings.

For instance, you could try to add a non-default setting of [-speeds rd,bw,lat](http://www.karlrunge.com/x11vnc/x11vnc_opts.html) in this line:
https://github.com/elgalu/docker-selenium/blob/master/vnc/bin/start-vnc.sh#L50

You will need to build the image and try it out.

If that doesn't help then we need to think about an alternative to x11vnc, I now remember @alexkogon mentioning he was using RDP instead of VNC, see:
https://github.com/SeleniumHQ/docker-selenium/issues/141#issuecomment-273043585

**Comment by dring1** [comment] 2017-05-08 16:46
Will be trying some flags, and possibly if I can get my hands on nvidia machine/instancehttps://github.com/NVIDIA/nvidia-docker and see if that will help the read speed as mentioned here: 
http://www.karlrunge.com/x11vnc/#limitations

**Comment by elgalu** [comment] 2017-05-15 16:51
So there were no VNC server settings that could help this case?

What about RDP instead of VNC?

**Comment by dring1** [comment] 2017-05-16 01:30
I've been looking into options, rdp was alright - but not a top performer.

Some non-free solutions do have great performance - but that would likely
be out of scope for this project.

**Comment by elgalu** [comment] 2017-07-31 08:45
As this seems to be only fixed with non-free solutions I'll close this issue for now.

Anyone interested in providing more information feel free to add it here or even send a PR!

**Closed by elgalu** 2017-07-31 08:45 UTC
Labels: enhancement, help-wanted
