### ISSUE TITLE
chrome not reachable 

### ISSUE THREAD

**Issue by eyal919** [elgalu/docker-selenium#55] opened 2015-12-27 17:05 UTC
Hi,
Chrome is craching and I can't fix it even look into all issues about it in the docker pages...

I'm running:
*docker run -d --name=grid \
  -p 4444:24444 -p 5810:5810 -p 5820:5820 -p 5830:5830 \
  -e SELENIUM_NODE_CH_PORT=25010 -e SELENIUM_NODE_FF_PORT=26010 \
  -e GRID=true -e CHROME=true -e FIREFOX=true \
  -e VNC_PASSWORD=hola -e VNC_PORT=5810 \
  -v /dev/shm:/dev/shm elgalu/selenium:2.48.2i*

then:
*docker run -d --name=node1 --net=container:grid \
  -e DISP_N=20 -e SSHD_PORT=22220 \
  -e SUPERVISOR_HTTP_PORT=29020 \
  -e SELENIUM_NODE_CH_PORT=25020 -e SELENIUM_NODE_FF_PORT=26020 \
  -e GRID=false -e CHROME=true -e FIREFOX=true \
  -e VNC_PASSWORD=hola -e VNC_PORT=5820 \
  -v /dev/shm:/dev/shm elgalu/selenium:2.48.2i*

While firefox run perfectly i'm having issues with chrome and getting: **org.openqa.selenium.WebDriverException: chrome not reachable** when running my test

I also mount /dev/shm to be 512M
> df -h
tmpfs                            512M     0  512M   0% /dev/shm

My vm is CentOS 7:
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  3882828 total,  2346076 free,   128372 used,  1408380 buff/cache
KiB Swap:  4063228 total,  3995524 free,    67704 used.  3508572 avail Mem

Thanks,

**Comment by elgalu** [comment] 2015-12-27 17:19
What about standalone? does this work:

```sh
docker pull elgalu/selenium:2.48.2i

docker run --rm --name=grid -p 4444:24444 -p 5920:25900 \
  -v /dev/shm:/dev/shm -e VNC_PASSWORD=hola elgalu/selenium:2.48.2i

docker exec grid wait_all_done 30s
```

Then run your tests against port `4444` in you CentOS host machine.

**Comment by eyal919** [comment] 2015-12-28 07:18
Thanks Leo,
The command above cuase the chrome command get timeout after 60sec.
But i find that 
  *ChromeOptions options = new ChromeOptions();
  options.addArguments("--no-sandbox");*
Did the work.

What do you think?

**Comment by elgalu** [comment] 2015-12-28 15:48
Good! Yeah now I remember [--no-sandbox](http://www.chromium.org/developers/design-documents/sandbox) mode is necessary for CentOS.

**Comment by elgalu** [comment] 2015-12-29 16:54
Please close this if the issue is solved ;)

**Closed** 2015-12-29 16:58 UTC
