### ISSUE TITLE
Record a selenium session

### ISSUE THREAD

**Issue by amitaibu** [elgalu/docker-selenium#29] opened 2015-06-25 06:25 UTC
@elgalu another support question, wondering if you know

Shoov is integrated with docker-selenium (currently on DEV, but it works really nice!), and my next thought is video recording the session, a la sauce labs. Do you have any experience with such a thing, or can provide some pointers?

**Comment by elgalu** [comment] 2015-06-26 07:46
Yes, video recording is in the roadmap, for know you can implement it yourself by reading https://github.com/elgalu/docker-selenium/issues/17#issuecomment-115564318

**Comment by elgalu** [comment] 2015-06-26 07:47
Closing as duplicate of #17

**Closed by elgalu** 2015-06-26 07:47 UTC
