### ISSUE TITLE
Currently only FireFox and Chrome are supported any plan of supporting Safari and I.E or edge

### ISSUE THREAD

**Issue by srijit-09** [elgalu/docker-selenium#267] opened 2018-08-27 07:10 UTC
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [ ] I provided my operating system name and version, e.g. output of `uname -a`

#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`

- [ ] If I don't have latest version of this image and can't upgrade, I will specify which one I'm using.

#### Docker version
- [x] I have latest version of docker and I will specify here the output of `docker --version`

- [ ] If I don't have latest version of docker I will specify which version with `docker --version` output

#### Docker-Compose
_(if using docker-compose)_

- [x] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

- [ ] If I don't have latest version of docker-compose I will specify which version with `docker-compose --version` output

**Comment by diemol** [comment] 2018-08-27 07:45
Hi @srijit-09,

This is a partial duplicate of #99, for Safari it is not possible either, as Apple only allows to run Apple software on Apple hardware.

**Closed by diemol** 2018-08-27 07:45 UTC
