### ISSUE TITLE
Tests failing with WebDriverError: cannot forward the request  post chrome version upgrade

### ISSUE THREAD

**Issue by remeltucker** [elgalu/docker-selenium#266] opened 2018-08-23 15:12 UTC
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [x] I provided my operating system name and version, e.g. output of `uname -a`
Linux
#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`
We modified the dockerfile to include the proxy urls
- [ ] If I don't have latest version of this image and can't upgrade, I will specify which one I'm using.

#### Docker version
- [x] I have latest version of docker and I will specify here the output of `docker --version`
17.05.0-ce
- [ ] If I don't have latest version of docker I will specify which version with `docker --version` output

#### Docker-Compose
_(if using docker-compose)_

- [ ] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

- [ ] If I don't have latest version of docker-compose I will specify which version with `docker-compose --version` output

Running tests with a elgalu/Selenium and Zalenium combo. Tests are running fine on Chrome 66. Recently upgraded to the latest image with support for Chrome68 and now tests are failing with

WebDriverError: cannot forward the request Connect to <ip> failed: Connection refused (Connection refused)

and in the browser driver log I could see the following

[1535025041.378][SEVERE]: bind() returned an error, errno=99: Cannot assign requested address (99)
[1535025041.378][INFO]: listen on IPv6 failed with error ERR_ADDRESS_INVALID

Not sure if this is the right place for this ticket. But are there any thoughts on this? or am I missing something?

**Comment by diemol** [comment] 2018-10-24 14:38
Is this still happen with Chrome 69 and Chrome 70?
How can we reproduce the issue?

**Comment by diemol** [comment] 2018-10-29 13:07
@remeltucker were you using a proxy to run the test?

**Comment by diemol** [comment] 2018-10-30 13:34
@remeltucker then the issue is the same as this one https://github.com/zalando/zalenium/issues/679, I added some explanation on this [comment](https://github.com/zalando/zalenium/issues/679#issuecomment-433008829).

You could try the proxy settings first with elgalu/selenium itself, when they work, then you could put them in Zalenium

**Comment by diemol** [comment] 2019-01-30 22:44
Closing as we didn't get any answer from the OP.

**Closed by diemol** 2019-01-30 22:44 UTC
Labels: waiting-retest
