### ISSUE TITLE
WebDriver .clear()  does not clear the text in text input

### ISSUE THREAD

**Issue by megolee** [elgalu/docker-selenium#333] opened 2019-07-17 10:14 UTC
## Operating System
Linux x86_64 GNU/Linux
#### Image version
Latest version 
#### Docker version
Docker version 18.06.1-ce, build e68fc7a215d7133c34aa18e3b72b4a21fd0c6136

I have tried with the latest image version and older version with chrome 74, 73, 72, 71, 70, these version of chrome are not work when execute clear action.

With the chrome version under 70 like 69(image verion 3.14.0-p10) and 68, these do work with clear command.

**Comment by diemol** [comment] 2019-07-20 01:46
Duplicate of https://github.com/SeleniumHQ/selenium/issues/6741
(summary, please use the Actions class)

**Closed by diemol** 2019-07-20 01:46 UTC

**Comment by megolee** [comment] 2019-07-23 07:42
@diemol But the same code,  clear() command works fine in SauceLab with chrome above 70
